django_project/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('', include('music.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music/urls.py
from django.urls import path
from music.views import (
                        landing_page,
						home,
						detail,
						my_albums,
						create_album,
						create_song,
						album_update,
						delete_song,
						song_update,
						delete_album,
						play_album,
						album_warning_message,
						song_warning_message,
						album_likes
					)

app_name = 'music'

urlpatterns = [
    path('', landing_page, name='landing_page'),
    path('home/', home, name='home'),
    path('album/<int:pk>/detail/', detail, name='detail'),
    path('user/<int:pk>/albums/', my_albums, name='my_albums'),
    path('new/album/', create_album, name='create_album'),
    path('album/<int:pk>/delete', delete_album, name='delete_album'),
    path('album/<int:pk>/add_song/', create_song, name='create_song'),
    path('album/<int:pk>/update/', album_update, name='album_update'),
    path('album/<int:album_pk>/song/<int:song_pk>/update/', song_update, name='song_update'),
	path('album/<int:album_pk>/song/<int:song_pk>/delete/', delete_song, name='song_delete'),
	path('page/not/found/', delete_album, name='page_404'),
	path('album/<int:pk>/play/', play_album, name='play_album'),
	path('album/<int:pk>/delete/message/', album_warning_message, name="album_warning_message"),
	path('album/<int:album_pk>/song/<int:song_pk>/delete/message/', song_warning_message, name="song_warning_message"),
	path('album/<int:pk>/likes', album_likes, name="album_likes")
]

users/urls.py
from django.urls import path
from users.views import register
from django.contrib.auth.views import LoginView, LogoutView
from users.views import profile

app_name = 'users'

urlpatterns = [
    path('register/', register, name='register'),
    path('user/<int:pk>/profile/', profile, name='profile'),
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='users/logout.html'), name='logout')
]

music/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from PIL import Image


class Category(models.Model):
    name = models.CharField(max_length=10)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Genres'


class Album(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=120)
    artist = models.CharField(max_length=100)
    genre = models.ForeignKey(Category, on_delete=models.CASCADE)
    date_added = models.DateTimeField(default=timezone.now)
    album_cover = models.ImageField(default='default_cover.jpg', upload_to='album_covers')
    likes = models.ManyToManyField(User, related_name="album_likes")

    class Meta:
        ordering = ["-date_added"]

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        img = Image.open(self.album_cover.path)
        if img.width > 500 or img.height > 500:
            new_img = (400, 400)
            img.thumbnail(new_img)
            img.save(self.album_cover.path)


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_song = models.FileField(upload_to="songs")
    title = models.CharField(max_length=120)
    file_type = models.CharField(max_length=10)
    date_added = models.DateTimeField(default=timezone.now)

    # class Meta:
    #     ordering = ["-date_added"]

    def __str__(self):
        return self.title

music/forms.py
from music.models import Album, Song
from django import forms


class CreateAlbumForm(forms.ModelForm):

    class Meta:
        model = Album
        fields = ['title', 'artist', 'genre', 'album_cover']

class CreateSongForm(forms.ModelForm):

    class Meta:
        model = Song
        fields = ['title', 'file_type', 'file_song']

class AlbumUpdateForm(forms.ModelForm):
	
    class Meta:
        model = Album 
        fields = ["title", "artist", "genre", "album_cover"]

class SongUpdateForm(forms.ModelForm):
	
    class Meta:
        model = Song
        fields = ["title", 'file_type', 'file_song']

music/views.py
from music.forms import CreateAlbumForm, CreateSongForm, AlbumUpdateForm, SongUpdateForm
from django.contrib.auth.decorators import login_required, user_passes_test
from django.shortcuts import render, redirect
from music.models import Album, Song, Category
from django.contrib.auth.models import User
from django.contrib import messages
from mutagen.mp3 import MP3
import math


def landing_page(request):
    return render(request, "music/landing_page.html", {})

def home(request):
    album_set = []
    albums = Album.objects.all()
    genres = Category.objects.all()
    for genre in genres:
        album_set += genre.album_set.all()[0:1]
    context = {
        'albums': albums,
        'album_set': album_set
    }
    return render(request, 'music/home.html', context)

@login_required
def detail(request, pk):
    album = Album.objects.get(pk=pk)
    return render(request, 'music/detail.html', {'album': album})


@login_required
def my_albums(request, pk):
    genres = []
    genre_count = {}
    total_genres = []
    max_num = 0
    user = User.objects.get(pk=pk)
    albums = user.album_set.all()
    for album in albums:
        if album.genre.name not in genres:
            genres.append(album.genre.name)
        total_genres.append(album.genre.name)
    for g in total_genres:
        genre_count[g] = total_genres.count(g)
    if not total_genres:
        max_num = 0
    else:
        max_num = max(genre_count.values())
    context = {
        'genres': genres,
        "max_num": max_num,
    }
    return render(request, 'music/my_albums.html', context)


@login_required
def create_album(request):
    if request.method == 'POST':
        form = CreateAlbumForm(request.POST, request.FILES)
        form.instance.user = request.user
        if form.is_valid():
            form.save()
            messages.success(request, f'User {request.user.username}, you have successfully created album "{form.instance}".')
            return redirect("music:home")
    else:
        form = CreateAlbumForm()
    return render(request, 'music/create_album.html', {'form': form})

@login_required
def album_update(request, pk):
    user = request.user
    album = Album.objects.get(pk=pk)
    albums = user.album_set.all()
    if album in albums:
        if request.method == "POST":
            album_update_form = AlbumUpdateForm(request.POST, request.FILES, instance=album)
            if album_update_form.is_valid():
                album_update_form.save()
                messages.success(request, f"Album \"{album}\" has been updated")
            return redirect("music:my_albums", pk=request.user.pk)
        else:
            album_update_form = AlbumUpdateForm(instance=album)
        context = {
            "album_update_form": album_update_form,
        }
        return render(request, "music/album_update.html", context)
    else:
        messages.success(request, f"Request denied. You are not authorized to update this album.")
    return redirect("music:detail", pk=pk)


@login_required
def delete_album(request, pk):
    album = Album.objects.get(pk=pk)
    user = request.user
    my_albums = user.album_set.all()
    if album in my_albums:
        album.delete()
        messages.success(request, f"Album \"{album}\" has been deleted")
        return redirect("music:my_albums", pk=user.id)
    else:
        context = {
            "message": "Sorry, your request has been denied."
        }
    return render(request, "music/404.html", context)


def album_warning_message(request, pk):
    album = Album.objects.get(pk=pk)
    user = request.user
    context = {
        "message": f"User {user.username}, are you sure you want to delete album \"{album}\"?",
        "album": album,
        "user": user
    }
    return render(request, "music/album_warning_message.html", context)


@login_required
def create_song(request, pk):
    user = request.user                 # request user
    albums = user.album_set.all()       # get users albums
    album = Album.objects.get(pk=pk)    # get the current album
    if album in albums:
        if request.method == 'POST':
            song_form = CreateSongForm(request.POST, request.FILES)
            song_form.instance.album = album # set it to the current album
            if song_form.is_valid():
                song_form.save()
                messages.success(request, f'User {request.user.username}, your song has been successfully added.')
            return redirect('music:detail', pk=pk)
        else:
            song_form = CreateSongForm()
        context = {
            "song_form": song_form
        }
        return render(request, 'music/create_song.html', context)
    else:
        messages.success(request, f"Request denied. You are not authorized to add song to this album.")
    return redirect("music:detail", pk=pk)


@login_required
def song_update(request, album_pk, song_pk):
    user = request.user
    album = Album.objects.get(pk=album_pk)
    albums = user.album_set.all()
    if album in albums:
        song = Song.objects.get(pk=song_pk)
        if request.method == "POST":
            song_update_form = SongUpdateForm(request.POST, instance=song)
            if song_update_form.is_valid():
                song_update_form.save()
                messages.success(request, f"Song \"{song}\" has been updated")
            return redirect("music:detail", pk=album_pk)
        else:
            song_update_form = SongUpdateForm(instance=song)
        context = {
            "song_update_form": song_update_form,
            "album_pk": album_pk,
            "song_pk": song_pk
        }
        return render(request, "music/song_update.html", context)
    else:
        song = Song.objects.get(pk=song_pk)
        messages.warning(request, "Request denied. You are not authorized to update this song.")
    return redirect("music:detail", pk=album_pk)


@login_required
def delete_song(request, album_pk, song_pk):
    user = request.user
    album = Album.objects.get(pk=album_pk)
    albums = user.album_set.all()
    if album in albums:
        songs = album.song_set.all()
        song = Song.objects.get(pk=song_pk)
        if song in songs:
            song.delete()
            messages.success(request, f"Song \"{song}\" has been deleted")
            return redirect("music:detail", pk=album_pk)
    else:
        context = {
            "message": "Sorry, your request has been denied."
        }
        return render(request, "music/404.html", context)

def song_warning_message(request, album_pk, song_pk):
    user = request.user
    album = Album.objects.get(pk=album_pk)
    albums = user.album_set.all()
    if album in albums:
        songs = album.song_set.all()
        song = Song.objects.get(pk=song_pk)
        user = request.user
        if song in songs:
            context = {
                "message": f"User {user.username}, are you sure you want to delete song \"{song}\"?",
                "album": album,
                "user": user,
                "song": song
            }
            return render(request, "music/song_warning_message.html", context)
    else:
        context = {
            "message": "Sorry, your request has been denied."
        }
        return render(request, "music/404.html", context)


def play_album(request, pk):
    song_length = []
    album = Album.objects.get(pk=pk)
    songs = album.song_set.all()
    for song in songs:
        audio = MP3(song.file_song)
        audio_length = audio.info.length
        minute = str(math.trunc((audio_length % 3600) / 60))
        second = str(math.trunc(audio_length % 60))
        if len(second) == 1:
            song_length.append(f"{minute}:0{second}")
        elif len(second) < 1:
            song_length.append(f"{minute}:00{second}")
        elif len(minute) < 1:
            song_length.append(f"0{minute}:{second}")
        else:
            song_length.append(f"{minute}:{second}")
    context = {
        "album": album,
        "song_length": song_length
    }
    return render(request, "music/play_album.html", context)


@login_required
def album_likes(request, pk):
    user = request.user
    album = Album.objects.get(pk=pk)
    users = album.likes.all()
    if user not in users:
        album.likes.add(user)
    else:
        pass
    print(user)
    print(users)
    return redirect("music:play_album" , pk=pk)

music/templates/music/album_update.html
{% extends "music/base.html" %}
{% load crispy_forms_tags %}

{% block title %}
    <title>Update Album</title>
{% endblock title %}

{% block navbar %}
{% endblock navbar %}

{% block image%}
{% endblock image%}

{% block content %}
<style>
    .requiredField {
        color: white;
    }
    label {
        margin-bottom: 0.3rem;
    }
    #div_id_title {
        margin-bottom: 0.5rem;
    }
    #div_id_artist {
        margin-bottom: 0.5rem;
    }
    #div_id_genre {
        margin-bottom: 0.5rem;
    }
    #div_id_album_cover div {
        color: rgb(255, 255, 255);
        font-size: 0.8rem;
    }
    #div_id_album_cover a {
        color: rgb(0, 128, 0);
        font-size: 0.8rem;
    }
    .form-group {
        margin-bottom: 0.5rem;
    }
    #id_album_cover {
        padding-top: 0rem !important;
        font-size: 0.8rem;
    }
    .form-control {
        padding-top: 0;
        padding-bottom: 0;
        border-radius: 0.3rem;
    }
    #id_title {
        border: none;
        outline: none;
        box-shadow: none;
    }
    #id_artist {
        border: none;
        outline: none;
        box-shadow: none;
    }
    #id_genre {
        border: none;
        outline: none;
        box-shadow: none;
    }
    #id_album_cover {
        border: none;
        outline: none;
        box-shadow: none;
    }
</style>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="album-update-form-container">
        <div class="album-update-form">
            <h3 class="album-update-form-title">Album Update</h3>
            {{ album_update_form|crispy }}
            <button class="album-update-btn">Update</button>
            <a class="album-update-form-cancel" href="{% url 'music:my_albums' user.pk %}" type="button">Cancel</a>
        </div>
    </div>
</form>
{% endblock content %}

{% block footer %}
{% endblock footer %}

music/templates/music/album_warning_message.html
{% extends "music/base.html" %}

{% block title %}
	<title>Warning</title>
{% endblock title %}

{% block content %}
<div class="album-warning-message-container">
	<p class="album-warning-message">{{ message }}</p>
	<div class="album-warning-message-btns">
		<a class="album-del-cancel-btn" type="button" href="{% url 'music:my_albums' user.pk %}">
			Cancel
		</a>
		<a class="album-delete-ok-btn" type="button" href="{% url 'music:delete_album' album.pk %}">
			Delete
		</a>
	</div>
</div>
{% endblock content %}

music/templates/music/create_album.html
{% extends 'music/base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    <title>New Album</title>
{% endblock title %}

{% block navbar %}
{% endblock navbar %}

{% block image%}
{% endblock image%}

{% block content %}
<style>
    #div_id_title {
        margin-bottom: 0.5rem;
    }
    #div_id_artist {
        margin-bottom: 0.5rem;
    }
    #div_id_genre {
        margin-bottom: 0.5rem;
    }
    #div_id_album_cover {
        margin-bottom: 0.5rem;
    }
    #id_album_cover {
        padding-top: 0rem !important;
        font-size: 0.8rem;
    }
    .requiredField {
        margin-bottom: 0.3rem !important;
    }
    #id_title {
        border: none;
        outline: none;
        box-shadow: none;
    }
    #id_artist {
        border: none;
        outline: none;
        box-shadow: none;
    }
    #id_genre {
        border: none;
        outline: none;
        box-shadow: none;
    }
    #id_album_cover {
        border: none;
        outline: none;
        box-shadow: none;
    }
    .form-control {
        padding-top: 0;
        padding-bottom: 0;
        border-radius: 0.3rem;
    }
</style>
<div class="album-form-row">
    <div class="album-form-col">
        <h3 class="create-ablum-title">Create Album</h3>
        <form method='POST' enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy}}
            <button class='album-submit-btn' type='submit'>Submit</button>
            <a class="album-form-cancel" href="{% url 'music:home' %}" type="button">Cancel</a>
        </form>
    </div>
</div>
{% endblock content %}

{% block footer %}
{% endblock footer %}

music/templates/music/create_song.html
{% extends 'music/base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    <title>Upload Song</title>
{% endblock title %}

{% block navbar %}
{% endblock navbar %}

{% block image%}
{% endblock image%}

{% block content %}
<style>
    #id_title {
        outline: none;
        box-shadow: none;
        border:none;
    }
    #id_file_type {
        outline: none;
        box-shadow: none;
        border:none;
    }
    #id_album_cover {
        outline: none;
        box-shadow: none;
        border:none;
    }
    .form-control {
        padding-top: 0;
        padding-bottom: 0;
        border-radius: 0.3rem;
    }
   .form-group {
        margin-bottom: 0.5rem;
    }
    label {
        margin-bottom: 0.3rem;
    }
    .form-control-file {
        font-size: 0.8rem;
    }
</style>
    <!-- {% if error_message %}
        {{ error_message }}
    {% else %} -->
<form method='POST' enctype="multipart/form-data">
    {% csrf_token %}
    <div class="create-song-form-row">
        <div class="create-song-form-col">
            <h3 class="create-song-form-title">Upload Song</h3>
            {{ song_form|crispy}}
            <button class='btn-add-song' type='submit'>Submit</button>
            <a class="song-form-cancel" href="{% url 'music:my_albums' user.pk %}" type="button">Cancel</a>
        </div>
    </div>
</form>
<!-- {% endif %} -->
{% endblock content %}

{% block footer %}
{% endblock footer %}

music/templates/music/detail.html
{% extends 'music/base.html' %}

{% block title %}
    <title>Album Detail </title>
{% endblock title %}

{% block image%}
{% endblock image%}

{% block content %}
<div class="album-detail-container">
    <div class="album-detail-row">
        <div class="album-detail-album-cover">
            {% if album in user.album_set.all %}
            <div class="album-detail-image-text">
                <img class="album-detail-album-image" src="{{ album.album_cover.url}}" alt="album_cover">
                <div class="album-detail-album-info-container">
                    <h5 class="album-detail-album-title">{{ album.title|truncatechars:15 }}</h5>
                    <small class="album-detail-album-artist">
                        Artist: {{ album.artist }}
                    </small>
                    <small class="album-detail-album-small">
                        Uplaoded By: {{ album.user.username }}
                    </small>
                    <small class="album-detail-album-small">
                        Date Added: {{ album.date_added|date:"F, d, Y" }}
                    </small>
                    <div class="album-detail-buttons">
                    {% if album in user.album_set.all %}
                        <a type="button" href="{% url 'music:album_update' album.pk %}" class="update-album-btn">Update</a>
                        <a type="button" href="{% url 'music:create_song' album.pk %}" class="add-song-btn">Add song</a>
                        <a type="button" href="{% url 'music:album_warning_message' album.pk %}" class="delete-album-btn">Delete</a>
                    {% endif  %}
                    </div>
                </div>
            </div>
            {% else %}
            <div class="album-detail-image-text">
                <img class="album-detail-album-image" src="{{ album.album_cover.url}}" alt="album_cover">
                <div class="album-detail-album-info-container">
                    <h5 class="album-detail-album-title">{{ album.title|truncatechars:15 }}</h5>
                    <small class="album-detail-album-small">
                        Artist: {{ album.artist }}
                    </small>
                    <small class="album-detail-album-small">
                        Uploaded By: {{ album.user.username }}
                    </small>
                    <small class="album-detail-album-small">
                        Date Added: {{ album.date_added|date:"F, d, Y" }}
                    </small>
                </div>
            </div>
            {% endif%}
        </div>
        <!-- end of album cover -->
        {% if not album.song_set.all %}
            <div class="album-detail-no-song-message">
                <div class="album-detail-no-song-text">
                    <p style="text-align: center;">There aren't any songs associated with this album.</p>
                </div>
            </div>
        {% else %}
            {% if album in user.album_set.all %}
                <div class="album-detail-song-container">
                    <div class="album-detail-list-songs">
                        <small class="album-detail-update-song-text">
                            Click song to update or delete.
                        </small>
                        <div class="album-detail-list-songs-text">
                            <small class="album-detail-list-songs-table-header1">
                                Title
                            </small>
                            <small class="album-detail-list-songs-table-header2">
                                Date Added
                            </small>
                            <small class="album-detail-list-songs-table-header3">
                                File
                            </small>
                        </div>
                        {% for song in album.song_set.all %}
                            <ul class="album-detail-ul">
                                <li class="album-detail-song-title">
                                    <a class="song-tile-a-link" href="{% url 'music:song_update' album.pk song.pk %}">
                                    {{ forloop.counter }}. {{ song.title|truncatechars:20 }}</a>
                                </li>
                                <li class="song-date-added">
                                    <small class="song-date-added-text">{{ song.date_added|date:"F, d, Y" }}</small>
                                </li>
                                <li class="song-file-type">
                                    <small class="song-file-type-text">{{ song.file_type }}</small>
                                </li>
                            </ul>
                        {% endfor %}
                    </div>
                </div>
            {% else %}
                <div class="album-detail-song-container">
                    <div class="album-detail-list-songs">
                        <div class="album-detail-list-songs-text">
                            <small class="album-detail-list-songs-table-header1">
                                Title
                            </small>
                            <small class="album-detail-list-songs-table-header2">
                                Date Added
                            </small>
                            <small class="album-detail-list-songs-table-header3">
                                File
                            </small>
                        </div>
                        {% for song in album.song_set.all %}
                        <ul class="album-detail-ul">
                            <li class="album-detail-song-title">
                                <a class="song-tile-a-link" href="#">
                                {{ song.title|truncatechars:15 }}</a>
                            </li>
                            <li class="song-date-added">
                                <small class="song-date-added-text">{{ song.date_added|date:"F, d, Y" }}</small>
                            </li>
                            <li class="song-file-type">
                                <small class="song-file-type-text">{{ song.file_type }}</small>
                            </li>
                        </ul>
                        {% endfor %}
                    </div>
                </div>
            {% endif %}
        {% endif %}
    </div>
</div>
{% endblock %}

music/templates/music/landing_page.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}">
    <title>Welcome to CloudBeat</title>
</head>
<body>
    <div class="landing-page-img">
        <div class="landing-page-bg-color">
            <div class="landing-page-content-conainer">
                <div class="landing-page-text-container">
                    <h1 class="landing-page-title">Welcome to CloudBeat</h1>
                    <p class="landing-page-para">
                        Join our community to share your latest creation of hits, and
                        discover and stream playlists from other artists like you from around the world.
                    </p>
                </div>
                <div class="landing-page-btns">
                    <a href="{% url 'users:register' %}" type="button" class="landing-page-sign-up-btn">
                        Sign up now
                    </a>
                    <a href="{% url 'music:home' %}" type="button" class="landing-page-explore-playlist-btn">
                        Explore playlist
                    </a>
                    <small class="landing-page-have-account">
                        Already have an account?
                        <a href="{% url 'users:login' %}" class="landing-page-signin-link">Sign in</a>
                    </small>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

music/templates/music/navbar.html
{% load static %}
  <div class="nav-container">
      <nav class="nav-bar-container">
          <div class="brand-name">
              <a class="brand" href="{% url 'music:home' %}">
                <img src="{% static 'music/cloud.png' %}" width="70px" alt="">
                <h5 class="brand-title">CloudBeat</h5>
              </a>
              <i class="fas fa-bars bar-btn"></i>
          </div>
          <div class="nav-items">
            {% if user.is_authenticated %}
              <a href="{% url 'music:home' %}" class="nav-item">home</a>
              <a href="{% url 'music:my_albums' user.pk %}" class="nav-item">my album</a>
              <a href="{% url 'music:create_album' %}" class="nav-item">new album</a>
              <a href="{% url 'users:profile' user.pk %}" class="nav-item">profile</a>
              <a href="{% url 'users:logout' %}" class="nav-item">sign out</a>
            {% else %}
              <a href="{% url 'music:home' %}" class="nav-item">home</a>
              <a href="{% url 'users:register' %}" class="nav-item">register</a>
              <a href="{% url 'users:login' %}" class="nav-item">sign in</a>
              <a href="{% url 'music:landing_page' %}" class="nav-item">exit site</a>
            {% endif %}
          </div>
      </nav>
  </div>

music/templates/music/song_update.html
{% extends "music/base.html" %}
{% load crispy_forms_tags %}

{% block title %}
    <title>Update Song</title>
{% endblock title %}

{% block navbar %}
{% endblock navbar %}

{% block image%}
{% endblock image%}

{% block content %}
<style>
   .form-group {
       margin-bottom: 0.5rem;
   }
   label {
       margin-bottom: 0.3rem;
   }
   #div_id_file_song div {
        font-size: 0.8rem;
   }
   #div_id_file_song a {
        color: green
   }
   .form-control {
        padding-top: 0;
        padding-bottom: 0;
        border-radius: 0.3rem;
    }
    #id_title {
        border: none;
        outline: none;
        box-shadow: none;
    }
    #id_file_type {
        border: none;
        outline: none;
        box-shadow: none;
    }
    #id_file_song {
        border: none;
        outline: none;
        box-shadow: none;
    }
</style>
    <form method="POST">
            {% csrf_token %}
        <div class="song-update-form-container">
            <div class="song-update-form">
                <div class="song-update-form-and-buttons">
                    <h3 class="song-update-form-title">Song Update Form</h3>
                    {{ song_update_form|crispy }}
                    <button class="song-update-btn">Update</button>
                    <a class="song-delete-btn" type="button"
                        href="{% url 'music:song_warning_message' album_pk song_pk %}">
                        Delete
                    </a>
                </div>
                <small class="song-update-form-cancel-text">
                    Click cancel to exit
                    <a class="song-update-form-cancel" href="{% url 'music:home' %}">Cancel</a>
                </small>
            </div>
        </div>
    </form>

{% endblock content %}

{% block footer %}
{% endblock footer %}

music/templates/music/song_warning_message.html
{% extends "music/base.html" %}


{% block title %}
	<title>Warning</title>
{% endblock title%}

{% block content %}
<div class="song-warning-message-container">
	<p class="song-warning-message">{{ message }}</p>
	<div class="song-warning-message-btns">
		<a class="song-del-cancel-btn" type="button" href="{% url 'music:my_albums' user.pk %}">
			Cancel
		</a>
		<a  class="song-delete-ok-btn" type="button" href="{% url 'music:song_delete' album.pk song.pk %}">
			Delete
		</a>
	</div>
</div>
{% endblock content %}