django_project/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('', include('music.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music/urls.py
from django.urls import path
from music.views import (
                        landing_page,
						home,
						detail,
						my_albums,
						create_album,
						create_song,
						album_update,
						delete_song,
						song_update,
						delete_album,
						play_album,
						album_warning_message,
						song_warning_message,
						album_likes
					)

app_name = 'music'

urlpatterns = [
    path('', landing_page, name='landing_page'),
    path('home/', home, name='home'),
    path('album/<int:pk>/detail/', detail, name='detail'),
    path('user/<int:pk>/albums/', my_albums, name='my_albums'),
    path('new/album/', create_album, name='create_album'),
    path('album/<int:pk>/delete', delete_album, name='delete_album'),
    path('album/<int:pk>/add_song/', create_song, name='create_song'),
    path('album/<int:pk>/update/', album_update, name='album_update'),
    path('album/<int:album_pk>/song/<int:song_pk>/update/', song_update, name='song_update'),
	path('album/<int:album_pk>/song/<int:song_pk>/delete/', delete_song, name='song_delete'),
	path('page/not/found/', delete_album, name='page_404'),
	path('album/<int:pk>/play/', play_album, name='play_album'),
	path('album/<int:pk>/delete/message/', album_warning_message, name="album_warning_message"),
	path('album/<int:album_pk>/song/<int:song_pk>/delete/message/', song_warning_message, name="song_warning_message"),
	path('album/<int:pk>/likes', album_likes, name="album_likes")
]

users/urls.py
from django.urls import path
from users.views import register
from django.contrib.auth.views import LoginView, LogoutView
from users.views import profile

app_name = 'users'

urlpatterns = [
    path('register/', register, name='register'),
    path('user/<int:pk>/profile/', profile, name='profile'),
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='users/logout.html'), name='logout')
]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='profile_images')

    def __str__(self):
        return '{} Profile'.format(self.user.username)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        img = Image.open(self.image.path)
        if img.width > 500 or img.height > 500:
            new_img = (400, 400)
            img.thumbnail(new_img)
            img.save(self.image.path)

users/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from users.models import Profile
from django import forms



class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class UserUpdateForm(forms.ModelForm):
	email = forms.EmailField()

	class Meta:
		model = User
		fields = ['username', 'email']

class ProfileUpdateForm(forms.ModelForm):
	class Meta:
		model = Profile 
		fields = ['image']
			


		

users/views.py
from django.shortcuts import render, redirect
from users.forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm
from django.contrib import messages
from users.models import Profile
from django.contrib.auth.decorators import login_required


def register(request):
    if request.method == "POST":
        form = UserRegisterForm(request.POST or None)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get("username")
            messages.success(request, f"Account has been created for {username}!")
            return redirect("users:login")
    else:
        form = UserRegisterForm()
    return render(request, "users/register.html", {"form": form})

@login_required
def profile(request, pk):
    profile = Profile.objects.get(pk=pk)
    print(profile.user)
    if request.method == "POST":
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, "{} profile has been updated".format(profile.user))
        return redirect("users:profile", pk=pk)
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)
    context = {
        'profile': profile,
        'u_form': u_form,
        'p_form': p_form
    }
    return render(request, 'users/profile.html', context)

users/templates/users/login.html
{% extends 'music/base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    <title>Sign In</title>
{% endblock title %}

{% block navbar%}
{% endblock navbar%}

{% block image%}
{% endblock image%}

{% block content %}
<style>
    .form-text {
        color: rgba(0, 0, 0, 0.7)!important;
        font-size: 0.7rem;
    }
    ul > li {
        margin-left: 1rem;
    }
    #div_id_username {
        margin-bottom: 0.7rem !important;
    }
    #div_id_password {
        margin-bottom: 0.7rem !important;
    }
    .requiredField {
        margin-bottom: 0.3rem !important;
    }
    #id_username {
        outline: none;
        box-shadow: none;
        border: none
    }
    #id_password {
        outline: none;
        box-shadow: none;
        border: none
    }
    .form-control {
        padding-top: 0;
        padding-bottom: 0;
        border-radius: 0.3rem;
    }
</style>
    <form method='POST'>
        {% csrf_token %}
        <div class="login-form-row">
            <div class="login-form-col">
                <h3 class="sign-in-form-title">Sign in</h3>
                {{ form|crispy}}
                <button class="sign-in-btn" type='submit'>Sign in</button>
                <a class="sign-in-cancel-btn" href="{% url 'music:home' %}" type="button">Cancel</a>
                <small class="not-registered">
                    Not yet registered?
                    <a class="sign-up-link" href="{% url 'users:register' %}">Sign up</a>
                </small>
            </div>
        </div>
    </form>
{% endblock content %}

{% block footer %}
{% endblock footer %}

users/templates/users/logout.html
{% extends 'music/base.html' %}

{% block title %}
    <title>Sign Out</title>
{% endblock title %}

{% block content %}
    <div class="logout-container">
        <div class='container-items'>
            <p class="signed-out">You Are Signed Out!</p>
            <small class="sign-in-again">
                <a href="{% url 'users:login' %}" class="sign-in-again-link">Sign in again</a>
            </small>
        </div>
    </div>
{% endblock content %}

users/templates/users/profile.html
{% extends "music/base.html" %}
{% load crispy_forms_tags %}

{% block title %}
	<title>Profile</title>
{% endblock title %}

{% block navbar %}
{% endblock navbar %}

{% block image%}
{% endblock image%}

{% block content %}
<style>
	#id_username {
		outline: none;
		border: none;
		box-shadow: none;
	}
	#id_email {
		outline: none;
		border: none;
		box-shadow: none;
	}
	#div_id_username {
		margin-bottom: 0.5rem;
	}
	#div_id_email {
		margin-bottom: 0.5rem;
	}
	#div_id_image {
		margin-bottom: 0.5rem;
	}
	#hint_id_username {
		display: none;
	}
	.requiredField {
		color:rgb(245, 239, 239);
	}
	#div_id_image div {
		color: rgb(245, 239, 239);
		font-size: 0.9rem;
	}
	#div_id_image div a{
		color: rgb(5, 150, 5);
		font-size: 0.8rem;
	}
	#div_id_image div {
		font-size: 0.8rem;
	}
	#id_image {
		font-size: 0.8rem;
		padding-top: 0.3rem;
		box-shadow: none;
		outline: none;
		border: none;
	}
	label {
		margin-bottom: 0.3rem;
	}
	.form-control {
		padding-top: 0;
		padding-bottom: 0;
		border-radius: 0.3rem;
	}
</style>
	<div class="row-profile">
		<div class="col-profile">
			<h3 class="profile-form-title">{{user.username|truncatechars:20}}'s Profile</h3>
			<div class="profile-image-text-container">
				<img class="profile-profile-image" src="{{profile.image.url}}" alt="profile image">
				<div class="profile-small-container">
					<small class="profile-username">{{ profile.user }}</small>
					<small class="profile-email">{{ profile.user.email}}</small>
				</div>
			</div>
			<div class="profile-form-container">
				<form method="POST" enctype="multipart/form-data">
					{% csrf_token %}
					{{ u_form|crispy }}
					{{ p_form|crispy }}
					<button class="profile-update-btn">Update</button>
					<a type=button href="{% url 'music:home' %}" class="profile-cancel-btn">Home</a>
				</form>
			</div>
		</div>
	</div>
{% endblock content %}

{% block footer %}
{% endblock footer %}

users/templates/users/register.html
{% extends 'music/base.html' %}
{% load crispy_forms_tags %}

{% block title%}
    <title>Sign Up</title>
{% endblock title%}

{% block navbar%}
{% endblock navbar%}

{% block image%}
{% endblock image%}

{% block content %}
<style>
/* from form */
/*ul li {
    margin-left: 1.5rem;
    font-size: 0.75rem;
}*/
/*.form-text {
    color: rgb(161, 161, 161)!important;
}*/
#hint_id_username {
    display: none;
}
#hint_id_password1 {
    display: none;
}
#hint_id_password2 {
    display: none;
}
#id_username {
    outline: none;
    box-shadow: none;
    border: none
}
#id_email {
    outline: none;
    box-shadow: none;
    border: none
}
#id_password1 {
    outline: none;
    box-shadow: none;
    border: none
}
#id_password2 {
    outline: none;
    box-shadow: none;
    border: none
}
#div_id_username {
    margin-bottom: 0.7rem !important;
}
#div_id_email {
    margin-bottom: 0.7rem !important;
}
#div_id_password1 {
    margin-bottom: 0.7rem !important;
}
#div_id_password2 {
    margin-bottom: 0.7rem !important;
}
.requiredField {
    margin-bottom: 0.3rem !important;
}
.form-control {
    padding-top: 0;
    padding-bottom: 0;
    border-radius: 0.3rem;
}
</style>
    <div class="register-form-row">
        <div class="register-form-col">
            <h3 class="register-form-title">Create your account</h3>
            <form method='POST'>
                {% csrf_token %}
                {{ form|crispy}}
                <button class="sign-up-btn" type='submit'>Sign Up</button>
                <a class="sign-up-cancel-btn" href="{% url 'music:home' %}" type="button">Cancel</a>
            </form>
            <small class="have-account">
                Already have an account?
                <a class="sign-in-link" href="{% url 'users:login' %}">Sign in</a>
            </small>
        </div>
    </div>
{% endblock content %}

{% block footer%}
{% endblock footer%}